defaults:
  - .@local: local
  - .@dataset: dataset
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
  
pos_weight: 2048
lr: 7e-4
l2_dec: 0
epochs: 30
model: "sat_sinr_mf"
sinr_layers: 8
sinr_hidden: 512
dropout: 0.3
embedder: "cnn_default"
tag: ""
checkpoint: None
validate: False

