sent_data_path: "/shares/wegner.ics.uzh/glc23_data/glc23_data/SatelliteImages/"
bioclim_lr_path: "/shares/wegner.ics.uzh/glc23_data/glc23_data/sinr_data/data/env/bioclim_elevation_scaled_europe.npy"
bioclim_path: "/shares/wegner.ics.uzh/glc23_data/bioclim+elev/bioclim_elevation_scaled_europe.npy"
dataset_file_path: "/shares/wegner.ics.uzh/glc23_data/glc23_data/Pot_10_to_1000.csv"
cp_dir_path: "/scratch/jdolli/sent-sinr/checkpoints"
logs_dir_path: "/scratch/jdolli/sent-sinr/wandb_logs"
val_data_path: "/shares/wegner.ics.uzh/glc23_data/glc23_data/Presence_Absence_surveys/loc_to_spec.csv"
gpu: True