sent_data_path: "glc23_data/SatelliteImages/"
bioclim_path: "glc23_data/bioclim+elev/bioclim_elevation_scaled_europe.npy"
dataset_file_path: "glc23_data/Pot_10_to_1000.csv"
cp_dir_path: "cps/"
logs_dir_path: "logs/"
test_data_path: "glc23_data/Presence_Absence_surveys/Presences_Absences_train.csv"
gpu: True